spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:safedrive}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    require-ssl: true

logging:
  level:
    com.safedrive: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/safe-drive/application.log
    max-size: 10MB
    max-history: 30

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}

app:
  upload:
    dir: ${UPLOAD_DIR:/var/safe-drive/uploads}
