spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://safedrive:JuStHilFqVJAdCg7HmHMiI51Heg0tDAZ@dpg-d3nk8149c44c73ebe0g0-a/safedrive_jp4y}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    require-ssl: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: when-authorized

logging:
  level:
    com.safedrive: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_LOG_LEVEL:WARN}
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/safe-drive.log}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
  http2:
    enabled: true

app:
  upload:
    dir: ${UPLOAD_DIR:/app/uploads}
    max-size: ${MAX_FILE_SIZE:50MB}
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyThatIsLongEnoughForHS256Algorithm}
    expiration: ${JWT_EXPIRATION:86400000}
  encryption:
    secret: ${ENCRYPTION_SECRET:MySecretKey12345}
